### PR TITLE
Port WSL hack. Also needed for Crouton on chromebooks.

### PR DESCRIPTION
**Pull request by arj03**
See https://github.com/yarnpkg/yarn/blob/master/src/util/network.js#L9

### CODE REVIEW

**Comment by arj03** [comment]
I'm trying to make scuttlebot work on a Chromebook and with this hack it doesn't crash anymore. But it keeps connecting to the same nodes over and over again, so this "fix" might have some unexpected side effects.

**Comment by dominictarr** [comment]
this seems reasonable. Is there another way we can detect onlineness on windows?
will merge

**Comment by dominictarr** [comment]
merged into 0.0.1 since this is a zero range I think we'll need to update things which depend on this.

**Comment by arj03** [comment]
Thanks. Seems like the connect is caused by frequent disconnects. I'll have to dig deeper but at least they are not directly related. I'll create a PR for updating the dependency in scuttlebot.

**Pull request merged**
